commands:
    build: go build -o bin/cbox ./cmd/cbox
    run: go run ./cmd/cbox
    test: go test ./...
env:
    - ANTHROPIC_API_KEY
host_commands:
    - git
    - gh
dockerfile: Dockerfile.cbox
workflow:
    branch: '{{.Slug}}'
    issue:
        create: gh issue create --title "$Title" --body "$Description" | grep -o '[0-9]*$'
        view: gh issue view "$IssueID" --json title,body,labels,state --template '{{.title}}\n\n{{.body}}'
        close: gh issue close "$IssueID"
        set_status: gh issue edit "$IssueID" --add-label "$Status"
        comment: gh issue comment "$IssueID" --body "$Body"
    pr:
        create: gh pr create --title "$Title" --body "$Description"
        merge: gh pr merge "$PRURL" --merge
